#!/bin/julia

#############################################
# Garamond script for TCP client operations #
#############################################
module GaramondWebClient

#TODO(Corneliu): Implement

end
